---
apiVersion: v1
kind: Namespace
metadata:
  name: reposync
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: prod
  namespace: reposync
  
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: https://github.com/chanduooo/bank-of-anthos.git
    revision: HEAD
    branch: dev
    dir: "kubernetes-manifests"
    auth: token
    secretRef:
      name: git-creds
    noSSLVerify: false
---
apiVersion: v1
data:
  token: Z2hwXzJzaThMbTEzVk0wMXA3RnZLYU5rOTFGT0lIZFdPdzN1U2tnWA==
  username: Y29vbHByYXNhZDE0MzJAZ21haWwuY29t
kind: Secret
metadata:
  name: git-creds
  namespace: reposync
type: Opaque

