---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bankdev # only set this field for a 'Role'
  name: bank-dev-role
rules:
# Update 'apiGroups' and 'resources' to reference actual resources managed by 'RepoSync'.
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]

---
# ROOT_REPO/namespaces/bank-dev/sync-rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: syncs-repo
  namespace: bankdev
subjects:
- kind: ServiceAccount
  name: ns-reconciler-bankdev
  namespace: config-management-system
roleRef:
  kind: Role
  name: bank-dev-role
  apiGroup: rbac.authorization.k8s.io
